// constants/specializations.js
module.exports = [
    { label: "الطب العام", value: "general_medicine" },
    { label: "طب الأطفال", value: "pediatrics" },
    { label: "أمراض النساء والتوليد", value: "gynecology_obstetrics" },
    { label: "طب العيون", value: "ophthalmology" },
    { label: "طب الأسنان", value: "dentistry" },
    { label: "الأمراض الجلدية", value: "dermatology" },
    { label: "طب القلب", value: "cardiology" },
    { label: "طب الأنف والأذن والحنجرة", value: "ent" },
    { label: "طب الأعصاب", value: "neurology" },
    { label: "جراحة العظام والمفاصل", value: "orthopedic_surgery" },
    { label: "الجراحة العامة", value: "general_surgery" },
    { label: "جراحة الأعصاب", value: "neurosurgery" },
    { label: "جراحة القلب والشرايين", value: "cardiovascular_surgery" },
    { label: "الطب النفسي", value: "psychiatry" },
    { label: "الأورام", value: "oncology" },
    { label: "طب الكلى", value: "nephrology" },
    { label: "أمراض الجهاز الهضمي", value: "gastroenterology" },
    { label: "أمراض الدم", value: "hematology" },
    { label: "التخدير والإنعاش", value: "anesthesia" },
    { label: "الأشعة والتصوير الطبي", value: "radiology" },
    { label: "الطب الشرعي", value: "forensic_medicine" },
    { label: "أمراض الصدر والتنفس", value: "pulmonology" },
    { label: "الطب الرياضي", value: "sports_medicine" },
    { label: "الطب الوقائي والصحة العامة", value: "public_health" },
    { label: "العلاج الطبيعي وإعادة التأهيل", value: "physiotherapy" },
];
